name: isp
description: Internal Support Page
version: 0.0.1

environment:
  sdk: '>=2.1.0-dev.5.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.2
  angular_router: ^2.0.0-alpha+19
  intl: ^0.15.7
  js: ^0.6.1+1
  uuid: ^1.0.3
  date_utils: ^0.1.0+2
  date_format: ^1.0.6
  http: ^0.11.0
  stream_transform: ^0.0.6
  dartson: ^1.0.0-alpha+3
  event_bus: ^1.0.1

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.3
  build_test: ^0.10.5
  build_web_compilers: ^1.0.0
  test: ^1.5.2
